#!/bin/ash

IFUP=/sbin/ifup
IFDOWN=/sbin/ifdown
NTPD=/etc/init.d/ntpd
UDHCPD=/etc/init.d/udhcpd
OPENVPN=/etc/init.d/openvpn

case "$2" in
    up)
        if   [ "$1" = "eth0" ] ; then
            $IFUP $1 &&	$NTPD start
	    $OPENVPN start
        elif [ "$1" = "eth1" ] ; then
            $UDHCPD start
        fi
        ;;
    down)
        if   [ "$1" = "eth0" ] ; then
            $IFDOWN $1
	    $NTPD stop
	    $OPENVPN stop
        elif [ "$1" = "eth1" ] ; then
	    $UDHCPD stop
        fi
        ;;
esac
exit 0
