#!/bin/ash

IFUP=/sbin/ifup
IFDOWN=/sbin/ifdown

NTPD=/etc/init.d/ntpd

UDHCPD=/usr/sbin/udhcpd
UDHCPD_PID=/var/run/udhcpd.pid

OPENVPN=/usr/sbin/openvpn

case "$2" in
    up)
        if   [ "$1" = "eth0" ] ; then
            $IFUP $1 &&	$NTPD start
        elif [ "$1" = "eth1" ] ; then
            $UDHCPD -S
        fi
        ;;
    down)
        if   [ "$1" = "eth0" ] ; then
            $IFDOWN $1 && $NTPD stop
        elif [ "$1" = "eth1" ] ; then
            start-stop-daemon -K -q -p $UDHCPD_PID
        fi
        ;;
esac
exit 0
