#!/bin/ash
IFPLUGD=/usr/sbin/ifplugd
ACTION=/etc/ifplugd/ifplugd.action
INTERFACES="eth0"
ARGS="-fI -u2 -d2 -pq"
[ -x $IFPLUGD ] || exit 0
case "$1" in
    start)
	echo -n "Starting ifplugd: "
	for IF in $INTERFACES; do
	    $IFPLUGD -r $ACTION -i $IF $ARGS
	    echo -n " $IF"
	done
	echo
	;;
    stop)
	echo -n "Shutting down ifplugd: "
	killall ifplugd
	;;
    restart)
	$0 stop $INTERFACES
	$0 start $INTERFACES
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1 
esac
exit 0
