#!/bin/ash
. /etc/init.d/functions
IFPLUGD=/usr/sbin/ifplugd
ACTION=/etc/ifplugd.action
INTERFACES="eth0 eth1"
ARGS="-fMI -u2 -d2"
[ -x $IFPLUGD ] || exit 1
case "$1" in
    start)
	for IF in $INTERFACES; do
	    $IFPLUGD -r $ACTION -i $IF $ARGS
	    check_status "Starting ifplugd on $IF"
	done
	;;
    stop)
	for IF in $INTERFACES; do
            PIDFILE="/var/run/ifplugd.$IF.pid"
            [ -f $PIDFILE ] && \
		start-stop-daemon -K -q -p $PIDFILE 
            check_status "Shutting down ifplugd on $IF"
        done
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1 
esac
exit 0
