#!/bin/ash
. /etc/init.d/functions
case "$1" in 
    start)
        /sbin/ifup -a > /dev/null
        check_status "Starting network"
	;;
    stop)
        /sbin/ifdown -a > /dev/null
        check_status "Stopping network"
	;;
    restart|reload)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
exit $?
