#!/bin/ash
. /etc/init.d/functions
echo -e "\nSystem is going down for reboot or halt now.\n"
for i in $(ls -r /etc/init.d/start/S??*)
do
    if [ -x $i ]; then
	$i stop
    fi
done
sync
check_status "Syncing all filesystems"
umount -a -r
check_status "Unmounting all filesystems"
