#!/bin/ash
. /etc/init.d/functions
echo -e "\nSystem is going down for reboot or halt now.\n"
echo "Starting stop scripts."
for i in /etc/init.d/stop/K*
do
    if [ -x $i ]; then
	$i stop
    fi
done
echo -n "Syncing all filesystems    : "
sync
check_status
echo -n "Unmounting all filesystems : "
umount -a -r
