#!/bin/ash
. /etc/init.d/functions

mount -n -t proc proc /proc
check_status "Mounting /proc"
echo 3 > /proc/sys/kernel/printk

mount -n -t sysfs sysfs /sys
check_status "Mounting /sys"

mount -o remount,rw /
check_status "Remounting Root RW"

mkdir /dev/pts
mount -t devpts devpts /dev/pts
check_status "Mounting /dev/pts"

mkdir /dev/shm
mount -t tmpfs none /dev/shm
check_status "Mounting Shared Memory"

echo "/sbin/mdev" > /proc/sys/kernel/hotplug
check_status "Enabling Hot-Plug"

mkdir /dev/input
mkdir /dev/snd
touch /dev/mdev.log
mdev -s
check_status "Populating /dev"

fsck -A -C -R -T -t nonnfs,nosmbfs
check_status "Checking Local Filesystems"

mount -a
check_status "Mounting Other Filesystems"

ln -s ../tmp /var/tmp
touch /var/run/utmp
touch /var/log/btmp
touch /var/log/wtmp
touch /var/log/lastlog
touch /var/log/messages
chmod 0664 /var/run/utmp
chmod 0664 /var/log/wtmp
chmod 0664 /var/log/btmp
chmod 0664 /var/log/lastlog
chmod 0660 /var/log/messages
check_status "Cleaning Up System"

hostname -F /etc/hostname
check_status "Setting Hostname"

ip addr add 127.0.0.1/8 dev lo
ip link set lo up

check_status "Setting up interface lo"

loadkmap < /etc/la-latin1.key
check_status "Loading Keyboard Map"

sleep 2
for i in $(ls /etc/init.d/start/S??*)
do
    if [ -x $i ]; then
	$i start
    fi
done
exit 0
