#!/bin/ash
. /etc/init.d/functions
case "$1" in
start)
	syslogd -s 0 -L
        check_status "Starting Syslogd"
	klogd
        check_status "Starting Klogd"
	;;
stop)
	killall klogd
        check_status "Stopping Klogd"
	killall syslogd
        check_status "Stopping Syslogd"
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
