#!/bin/ash
. /etc/init.d/functions
case "$1" in
start)
	echo -n "Starting syslogd : "
	syslogd -s 0 -L
	check_status
	echo -n "Starting klogd   : "
	klogd
	check_status
	;;
stop)
	echo -n "Stopping klogd   : "
	killall klogd
	check_status
	echo -n "Stopping syslogd : "
	killall syslogd
	check_status
	;;
restart)
	$0 stop
	$0 start
	;;
*)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac
# End /etc/init.d/syslog
